export const SET_GENRE = "SET_GENRE";
export const FETCH_GENRE = "FETCH_GENRE";
export const GENRE_ERROR = "GENRE_ERROR";
export const FETCH_GENRE_ARTISTS = "FETCH_GENRE_ARTISTS";
export const SET_GENRE_ARTISTS = "SET_GENRE_ARTISTS";
export const CLEAR_ARTISTS = "CLEAR_ARTISTS";
